CREATE TABLE temps (
  id      INTEGER NOT NULL PRIMARY KEY,
  hi_temp INTEGER NOT NULL
  );

INSERT INTO temps VALUES( 1,49);
INSERT INTO temps VALUES( 2,46);
INSERT INTO temps VALUES( 3,48);
INSERT INTO temps VALUES( 4,50);
INSERT INTO temps VALUES( 5,50);
INSERT INTO temps VALUES( 6,50);
INSERT INTO temps VALUES( 7,51);
INSERT INTO temps VALUES( 8,52);
INSERT INTO temps VALUES( 9,53);
INSERT INTO temps VALUES(10,50);
INSERT INTO temps VALUES(11,50);
INSERT INTO temps VALUES(12,47);
INSERT INTO temps VALUES(13,50);
INSERT INTO temps VALUES(14,51);
INSERT INTO temps VALUES(15,52);
